# Generated by Django 5.1.7 on 2025-04-09 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('artista', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='canciones/img/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='canciones/audio/')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('team1_score', models.IntegerField(default=0)),
                ('team2_score', models.IntegerField(default=0)),
                ('game_started', models.BooleanField(default=False)),
                ('game_finished', models.BooleanField(default=False)),
                ('ganador', models.CharField(blank=True, max_length=50, null=True)),
                ('rondas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Sencilla', 'Sencilla'), ('Doble', 'Doble'), ('Triple', 'Triple')], max_length=50)),
                ('ronda', models.IntegerField(default=0)),
                ('terminada', models.BooleanField(default=False)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adivinacancion.juego')),
            ],
        ),
        migrations.CreateModel(
            name='CancionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=100)),
                ('robo', models.BooleanField(default=False)),
                ('equipo_robo', models.CharField(blank=True, max_length=100, null=True)),
                ('terminada', models.BooleanField(default=False)),
                ('ganador', models.CharField(blank=True, max_length=100, null=True)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adivinacancion.cancion')),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adivinacancion.ronda')),
            ],
        ),
    ]
