# Generated by Django 5.1.7 on 2025-04-09 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adivinacancion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='cancion',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adivinacancion.artista'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adivinacancion.genero'),
        ),
    ]
