# Generated by Django 5.1.7 on 2025-04-09 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adivinacancion', '0002_artista_genero_remove_cancion_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='rondas',
        ),
        migrations.AddField(
            model_name='artista',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artistas', to='adivinacancion.genero'),
        ),
    ]
