# Generated by Django 5.1.7 on 2025-04-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adivinacancion', '0003_remove_cancion_genero_remove_juego_rondas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='rondas',
            field=models.IntegerField(default=0),
        ),
    ]
