# Generated by Django 5.1.7 on 2025-04-16 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juego', models.CharField(choices=[('Boxeo', 'Boxeo'), ('Martillo', 'Martillo'), ('Vencidas', 'Vencidas'), ('Toques', 'Toques')], default='Boxeo', max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('monto', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MonedaInsertada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('moneda', models.IntegerField(blank=True, null=True)),
                ('pulsos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReinicioCreditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('valor_anterior', models.IntegerField()),
                ('nuevo_valor', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='juegos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegosfuerza.juego')),
            ],
        ),
    ]
