# Generated by Django 5.1.7 on 2025-03-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('pregunta', models.TextField()),
                ('respuesta1', models.CharField(max_length=50)),
                ('respuesta2', models.CharField(max_length=50)),
                ('respuesta3', models.CharField(max_length=50)),
                ('respuesta4', models.CharField(max_length=50)),
                ('respuesta5', models.CharField(max_length=50)),
                ('calificacion1', models.IntegerField()),
                ('calificacion2', models.IntegerField()),
                ('calificacion3', models.IntegerField()),
                ('calificacion4', models.IntegerField()),
                ('calificacion5', models.IntegerField()),
            ],
        ),
    ]
