# Generated by Django 5.1.7 on 2025-03-10 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cienmexicanos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='calificacion1',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='calificacion2',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='calificacion3',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='calificacion4',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='calificacion5',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta1',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta2',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta3',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta4',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta5',
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cienmexicanos.pregunta')),
            ],
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cienmexicanos.tipo'),
        ),
    ]
