# Generated by Django 5.1.7 on 2025-03-14 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cienmexicanos', '0002_tipo_remove_pregunta_calificacion1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('team1_score', models.IntegerField(default=0)),
                ('team2_score', models.IntegerField(default=0)),
                ('timer', models.IntegerField(default=60)),
                ('game_started', models.BooleanField(default=False)),
                ('game_finished', models.BooleanField(default=False)),
                ('ganador', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.IntegerField()),
                ('errores', models.IntegerField(default=0)),
                ('robo', models.BooleanField(default=False)),
                ('turno', models.CharField(max_length=50)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cienmexicanos.juego')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cienmexicanos.pregunta')),
            ],
        ),
    ]
