# Generated by Django 5.1.7 on 2025-03-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cienmexicanos', '0003_juego_ronda'),
    ]

    operations = [
        migrations.AddField(
            model_name='ronda',
            name='ganador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
