# Generated by Django 5.1.7 on 2025-03-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cienmexicanos', '0004_ronda_ganador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='timer',
        ),
    ]
