# Generated by Django 5.1.7 on 2025-03-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cienmexicanos', '0005_remove_juego_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ronda',
            name='terminada',
            field=models.BooleanField(default=False),
        ),
    ]
