# Generated by Django 5.1.7 on 2025-03-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cienmexicanos', '0005_creditos'),
        ('cienmexicanos', '0006_ronda_terminada'),
    ]

    operations = [
    ]
