# Generated by Django 5.1.7 on 2025-03-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cienmexicanos', '0007_merge_0005_creditos_0006_ronda_terminada'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonedaInsertada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('moneda', models.IntegerField(blank=True, null=True)),
                ('pulsos', models.IntegerField()),
            ],
        ),
    ]
