# Generated by Django 5.1.7 on 2025-03-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cienmexicanos', '0007_merge_0005_creditos_0006_ronda_terminada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ronda',
            name='tipo',
            field=models.CharField(default='Sencilla', max_length=50),
        ),
    ]
