# Generated by Django 5.1.7 on 2025-03-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cienmexicanos', '0008_monedainsertada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReinicioCreditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('valor_anterior', models.IntegerField()),
                ('valor_seteado', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
