# Generated by Django 5.1.7 on 2025-03-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cienmexicanos', '0009_reiniciocreditos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteCreditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valor_anterior', models.IntegerField()),
                ('nuevo_valor', models.IntegerField()),
            ],
        ),
    ]
