# Generated by Django 5.1.7 on 2025-03-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cienmexicanos', '0010_ajustecreditos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AjusteCreditos',
        ),
    ]
