# Generated by Django 5.1.7 on 2025-03-24 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cienmexicanos', '0011_delete_ajustecreditos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reiniciocreditos',
            old_name='valor_seteado',
            new_name='nuevo_valor',
        ),
    ]
