# Generated by Django 5.1.7 on 2025-03-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cienmexicanos', '0008_ronda_tipo'),
        ('cienmexicanos', '0012_rename_valor_seteado_reiniciocreditos_nuevo_valor'),
    ]

    operations = [
    ]
