# Generated by Django 5.1.7 on 2025-04-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cienmexicanos', '0013_merge_20250324_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='preguntas_ronda',
            field=models.IntegerField(default=2),
        ),
    ]
