# Generated by Django 5.1.7 on 2025-04-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cienmexicanos', '0014_juego_preguntas_ronda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='preguntas_ronda',
        ),
    ]
