# Generated by Django 5.1.7 on 2025-04-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cienmexicanos', '0015_remove_juego_preguntas_ronda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Creditos',
        ),
        migrations.DeleteModel(
            name='MonedaInsertada',
        ),
        migrations.DeleteModel(
            name='ReinicioCreditos',
        ),
    ]
