# Generated by Django 5.1.7 on 2025-03-26 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('team1_score', models.IntegerField(default=0)),
                ('team2_score', models.IntegerField(default=0)),
                ('game_started', models.BooleanField(default=False)),
                ('game_finished', models.BooleanField(default=False)),
                ('ganador', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Abierta', 'Abierta'), ('Opciones', 'Opciones')], default='Abierta', max_length=50)),
                ('grado', models.CharField(choices=[('1ero', '1ero'), ('2do', '2do'), ('3ero', '3ero'), ('4to', '4to'), ('5to', '5to'), ('6to', '6to')], default='1ero', max_length=50)),
                ('materia', models.CharField(choices=[('Matematicas', 'Matematicas'), ('Español', 'Español'), ('Ciencias Naturales', 'Ciencias Naturales'), ('Ciencias Sociales', 'Ciencias Sociales'), ('Geografia', 'Geografia'), ('Historia', 'Historia'), ('Artes', 'Artes')], default='Matematicas', max_length=50)),
                ('pregunta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primaria.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='Sencilla', max_length=50)),
                ('ronda', models.IntegerField(default=0)),
                ('terminada', models.BooleanField(default=False)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primaria.juego')),
                ('pregunta_team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_team1', to='primaria.pregunta')),
                ('pregunta_team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_team2', to='primaria.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=100)),
                ('puntos', models.IntegerField(default=0)),
                ('robo', models.BooleanField(default=False)),
                ('equipo_robo', models.CharField(blank=True, max_length=100, null=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primaria.pregunta')),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primaria.ronda')),
            ],
        ),
    ]
