# Generated by Django 5.1.7 on 2025-03-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ronda',
            name='pregunta_team1',
        ),
        migrations.RemoveField(
            model_name='ronda',
            name='pregunta_team2',
        ),
    ]
