# Generated by Django 5.1.7 on 2025-03-27 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primaria', '0002_remove_ronda_pregunta_team1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntaequipo',
            name='puntos',
        ),
    ]
