# Generated by Django 5.1.7 on 2025-03-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primaria', '0003_remove_preguntaequipo_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntaequipo',
            name='terminada',
            field=models.BooleanField(default=False),
        ),
    ]
