# Generated by Django 5.1.7 on 2025-04-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primaria', '0004_preguntaequipo_terminada'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='preguntas_ronda',
            field=models.IntegerField(default=2),
        ),
    ]
