# Generated by Django 5.1.7 on 2025-04-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primaria', '0005_juego_preguntas_ronda'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntaequipo',
            name='ganador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
