# Generated by Django 5.1.7 on 2025-05-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='cancion',
        ),
        migrations.AddField(
            model_name='cancion',
            name='archivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
